### ISSUE TITLE
Crypto: soften the requirement for concurrency

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARM-software/psa-api#134]
According to [version 1.1 of the crypto API specification](https://arm-software.github.io/psa-api/crypto/1.1/overview/conventions.html#concurrent-calls):

> Concurrent calls are performed correctly, as if the calls were executed in sequence, provided that [not important here]

The intent is that this only holds for functional correctness. For example, at any given point in time, a key identifier either exists or doesn't exist, there isn't some other state where querying the key identifier says it doesn't exist but attempting to create it returns `ALREADY_EXISTS`. But this doesn't hold for all observations. Specifically, it is possible, and [generally desirable](https://github.com/Mbed-TLS/mbedtls/pull/8618#discussion_r1430640587), that library calls are not linearizable with respect to resource exhaustion. For example, it should be permitted that, starting from a given system state, with one thread calling `f1()` and another thread calling `f2()`:

* both calls succeed, with `f1()` taking place before `f2()` (if the order is observable);
* both calls succeed, with `f2()` taking place before `f1()` (if the order is observable);
* At least one of the calls in `f1() || f2()` fails due to some resource exhaustion (e.g. `PSA_ERROR_INSUFFICIENT_MEMORY`, `PSA_ERROR_INSUFFICIENT_STORAGE`, `PSA_ERROR_COMMUNICATION_FAILURE`).

This is in keeping with the general intent of the crypto API specification, which never makes any guarantee of availability. But it violates the letter of the statement quoted above.

**Comment by athoelke** [comment]
I've just posted a PR to try and find good wording for this, that doesn't become incomprehensible.

To help with understanding the rule, I have provided an example or a scenario and some statements about the valid results.
