### ISSUE TITLE
Crypto PAKE Extension : Review of Release Candidate

### ISSUE THREAD

**Issue by athoelke** [ARM-software/psa-api#141]
_[Updated: RC3 includes feedback from RC1 (#155, #156, and #159), and updates the API status to Final (#160)]_
_[Updated: RC2 failed to include (#155 & #156)]_

PDF for review: [AES0058-PSA_Certified_Crypto_API-1.2_PAKE_Extension.0-rc3.pdf](https://github.com/ARM-software/psa-api/files/14112449/AES0058-PSA_Certified_Crypto_API-1.2_PAKE_Extension.0-rc3.pdf)
~~Candidate 2: [AES0058-PSA_Certified_Crypto_API-1.2_PAKE_Extension.0-rc2.pdf](https://github.com/ARM-software/psa-api/files/14099918/AES0058-PSA_Certified_Crypto_API-1.2_PAKE_Extension.0-rc2.pdf)~~
~~Candidate 1: [AES0058-PSA_Certified_Crypto_API-1.2_PAKE_Extension-bet.2-rc1.pdf](https://github.com/ARM-software/psa-api/files/13890452/AES0058-PSA_Certified_Crypto_API-1.2_PAKE_Extension-bet.2-rc1.pdf)~~

This update adds support for SPAKE2+, and updates the API following feedback from implementation of the original PAKE interface. See the related issues and PRs in the [Final Milestone](https://github.com/ARM-software/psa-api/milestone/8?closed=1).

Please provide feedback about anything that is unclear, confusing, missing, or incorrect; so we can finalize the document for publication.

**Comment by athoelke** [comment]
New release candidate RC2, includes feedback from RC1 (#155, #156, and #159), and updates the API status to Final (#160).

**Comment by athoelke** [comment]
> New release candidate RC2, includes feedback from RC1 (#155, #156, and #159), and updates the API status to Final (#160).

Processing error - I forgot to include #155 and #156 into the RC2 build. RC3 now available.

**Comment by oberon-sk** [comment]
RC3 looks good to us, thanks!

**Comment by oberon-sk** [comment]
Thanks Andrew,
that‘s really awesome!
Best 
Stephan
