### ISSUE TITLE
Relax the definition of 'persistent staging'

### ISSUE THREAD

**Issue by athoelke** [ARM-software/psa-api#69]
The investigation for the solution (PR #49) for issue #5 identified some challenges in the definition of 'persistent staging' for the API. This was partially exposed by #48, where the effect of 'volatile staging' on the state model is explicitly documented.

As currently defined, the state model for 'persistent staging' &mdash; components that do not set the `PSA_FWU_VOLATILE_STAGING` flag &mdash; presents challenges for implementations to manage the persistent state model in flash memory. The investigation also identified that most OTA solutions today do not expect downloaded firmware images (in particular, partially downloaded ones) to be retained over a reboot.

It seems that the default position for the FWU API, where a partially written image (state WRITING) is preserved on reboot, is both difficult to implement efficiently, and significantly beyond current practice.

Additionally:

* Resuming the download of a partially prepared image (in WRITING state) following a reboot, requires synchronization between the update server, update client, and the firmware store, to determine the current status. The assumption (in the current spec) is that this will require implementation-defined API to achieve.
* Retaining a fully prepared image (in CANDIDATE state) over a reboot, has substantially less complexity, and might be important for some use cases. For example, if the 'download' and 'apply update' commands from the update server to the update client are separate, and could be separated by a significant time delay.

Therefore, there is value in having the API permit an implementation to support persistence of CANDIDATE images, but not of WRITING images.

### Proposal

Relax the definition of 'persistent staging', so that this only additionally requires CANDIDATE state to be retained after reboot (compared to volatile staging), and allow it to be implementation-defined whether WRITING, FAILED, and UPDATE states are retained/visible following a reboot.

We could also define additional component flags to indicate if WRITING, FAILED, and UPDATE states are persistent? Alternatively, we we could defer standardization of such flags, and also any API that might support resuming a download, until we have a concrete implementation of that use case.

We could rename the current `PSA_FWU_VOLATILE_STAGING` flag, to better fit the finer-grained options that are proposed here.

**Comment by bulislaw** [comment]
Looks good to me. Retaining CANDIDATE state is relatively simple and having it defined in the spec makes sense.

I'm not sure if defining extra flags to indicate persistence of other states would be useful now. It feels like the whole software stack needs to be well integrated to support it, so the flag in the service probably won't be used anyway.

As for resumption of download we should probably defer it until we have a partner interested in implementing it as it may be quite tricky to write the spec without a prototype at least.
