### ISSUE TITLE
Release Candidate *2* for Firmware Update API 1.0.0

### ISSUE THREAD

**Issue by athoelke** [ARM-software/psa-api#72]
**Updated**: Following RC1 review, RC2  adds clarifications for some of the API concepts, improved consistency, and included an additional threat in the SRA.

Since RC1, the differences can be found in PR #68 (commits following https://github.com/ARM-software/psa-api/pull/68/commits/3dc2fe8162257a8eda5f485bae677e42b6a44e54), and all the commits in PR #79.  

**PDF for review**: [IHI0093-PSA_Certified_Firmware_Update_API-1.0.0-rc2.pdf](https://github.com/ARM-software/psa-api/files/12162972/IHI0093-PSA_Certified_Firmware_Update_API-1.0.0-rc2.pdf)
~~**PDF for review**: IHI0093-PSA_Certified_Firmware_Update_API-1.0.0-rc1.pdf~~

This includes all merged and proposed changes since 1.0-beta, including #48, #49, #68, and #71.

The change history in Appendix E provides a summary of the changes, and links to the primary sections that are impacted. For a detailed diff of the changes, see the _Files changed_ tab for the specific Pull Request.

Please provide feedback about anything that is unclear, confusing, missing, or incorrect; so we can finalize the document for publication.

**Comment by stevew817** [comment]
Page 16: unclear sentence "Downloading and installing updates must be reliable to wasting energy on..."

**Comment by athoelke** [comment]
> Page 16: unclear sentence "Downloading and installing updates must be reliable to wasting energy on..."

Thank you - a missing word, it was meant to say: "Downloading and installing updates must be reliable to __avoid__ wasting energy on..."

**Comment by athoelke** [comment]
Release Candidate 2: There has been enough feedback from RC1 to justify publishing an updated Release Candidate for final review.

I've updated the issue description above with a new PDF for RC2, and links to the PRs and commits with the changes between RC1 and RC2.

**Comment by athoelke** [comment]
RC2 review has concluded.
